openapi: 3.0.0
info:
  title: Petstore API
  description: API for managing pets
  version: 1.0.0
paths:
  /pets:
    get:
      summary: Retrieve a list of pets
      description: Returns a list of all pets in the store.
      responses:
        "200":
          $ref: "#/components/responses/PetListResponse"
    post:
      summary: Add a new pet
      description: Creates a new pet in the store.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet" # Use Pet schema for request body
      responses:
        "201":
          $ref: "#/components/responses/PetCreatedResponse"
        "400":
          $ref: "#/components/responses/BadRequestResponse"

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          example: 2
          description: The unique identifier for the pet.
        name:
          type: string
          example: "Rex"
          description: The name of the pet.
        type:
          type: string
          example: "Dog"
          description: The type or species of the pet.
    PetList:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
      description: A list of pet objects.
    Error:
      type: object
      properties:
        error:
          type: string
          example: "Invalid request body"
          description: Error message indicating why the request failed.

  responses:
    PetListResponse:
      description: A list of pets
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PetList"
    PetCreatedResponse:
      description: Pet created successfully
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pet"
    BadRequestResponse:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
