openapi: 3.0.0
info:
  title: Pet Store API
  description: A simple API for managing pets.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: The API server

paths:
  /pets:
    get:
      summary: List all pets
      description: Retrieve a list of all pets.
      responses:
        "200":
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"

    post:
      summary: Create a pet
      description: Add a new pet to the store.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "201":
          description: Pet created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"

  /pets/{petId}:
    get:
      summary: Get a pet by ID
      description: Retrieve details of a pet by its ID.
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A pet object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        "404":
          description: Pet not found

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: string
          example: "123"
        name:
          type: string
          example: "Fluffy"
        status:
          type: string
          description: The status of the pet
          enum:
            - available
            - pending
            - sold
